hypersites_course:
    resource: "@HypersitesCourseBundle/Controller/"
    type:     annotation
    prefix:   /

hypersites_commercial_supplier:
    resource: "@HypersitesCommercialSupplierBundle/Controller/"
    type:     annotation
    prefix:   /

hypersites_tourism:
    resource: "@HypersitesTourismBundle/Controller/"
    type:     annotation
    prefix:   /

hypersites_cliente:
    resource: "@HypersitesClienteBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

