<?php

namespace Hypersites\ClienteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClassAttendenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassAttendenceRepository extends EntityRepository
{
}
